# Generated by Django 3.2.14 on 2022-07-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=24, unique=True)),
                ('abrv', models.CharField(max_length=2)),
                ('avg_price_per_kwh', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
