# Generated by Django 3.2.14 on 2022-07-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
