# Generated by Django 3.2.14 on 2022-07-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0002_btcprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='avg_price_per_kwh',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
