# Generated by Django 3.2.13 on 2022-05-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(max_length=200, upload_to='')),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('py', 'PYTHON'), ('c', 'C'), ('cpp', 'C++'), ('cshp', 'C#'), ('r', 'R'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JAVASCRIPT'), ('juli', 'JULIA')], max_length=4)),
            ],
        ),
    ]
