# Generated by Django 3.2.13 on 2022-06-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='file',
            field=models.FileField(max_length=200, upload_to='code/'),
        ),
    ]
