# Generated by Django 3.2.13 on 2022-06-15 22:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebank', '0003_alter_codefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/Users/wnoland/CS50W/capstone/code/'), upload_to='code/'),
        ),
    ]
