# Generated by Django 3.2.13 on 2022-06-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebank', '0004_alter_codefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codefile',
            name='file',
            field=models.FilePathField(path='/Users/wnoland/CS50W/capstone/code/'),
        ),
    ]
