# Generated by Django 3.2.13 on 2022-06-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codebank', '0005_alter_codefile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codefile',
            old_name='file',
            new_name='filepath',
        ),
    ]
