# Generated by Django 3.2.13 on 2022-06-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebank', '0006_rename_file_codefile_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='inputs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='codefile',
            name='output',
            field=models.CharField(choices=[('dict', 'DICTIONARY'), ('list', 'ARRAY'), ('bool', 'BOOLEAN'), ('int', 'INTEGER'), ('float', 'FLOAT'), ('str', 'STRING')], default='integer', max_length=10),
        ),
    ]
