# Generated by Django 3.2.13 on 2022-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20220511_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='follows',
            name='isfollowing',
            field=models.BooleanField(default=False),
        ),
    ]
